### ISSUE TITLE
Does not creates Zip file as output parameter

### ISSUE THREAD

**Issue by mcpgeo** [Acumatica/CustomizationBuildScript#1]
Hello,
I want to use CommandLine.exe tool in order to generate an package file.
So, we write following CMD:

C:\Program Files (x86)\Acumatica ERP2018R1\Files\Bin>PX.CommandLine.exe method BuildProject /website "C:\Program Files (x86)\Acumatica ERP\AcuErpTBC-Dev" /in "C:\Program Files (x86)\Acumatica ERP\AcuErpTBC-Dev\App_Data\Builds\Temp" /out "C:\Builds\AcuErpTBC.zip" /description "Test"

The CMD creates C:\Builds\ folder within all necessary sub folders and xml files but NOT the package itself.

**Comment by killercat4e** [comment]
Hi, all arguments should start with "/", method too, so it should be "/method BuildProject" rather than "method BuildProject".

**Comment by mcpgeo** [comment]
UNfortunately, this is not a reason

**Comment by killercat4e** [comment]
What version of acumatica is in "C:\Program Files (x86)\Acumatica ERP\AcuErpTBC-Dev" folder? 
Could you, please, show contents of "C:\Program Files (x86)\Acumatica ERP\AcuErpTBC-Dev\App_Data\Builds\Temp" before running of this script and contents of "C:\Builds\" after running it?

**Comment by mcpgeo** [comment]
The reason was old version of acumatica.

Sorry for inappropriate issues
